name: bench
on: workflow_dispatch
jobs:
  bench:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: bench
        run: |
          git clone https://boringssl.googlesource.com/boringssl
          cd boringssl
          mkdir build
          cd build
          
          # Обязательно собираем в Release! Иначе бенчмаркинг не имеет смысла.
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release ..
          ninja
          
          # Запускаем бенчмарки через crypto_test (фильтруем по AES)
          # Флаг --gtest_filter="-" отключает обычные тесты, чтобы запускались ТОЛЬКО бенчмарки
          taskset -c 0 ./bssl_bench --benchmark_filter="AES"
