name: compile
on: workflow_dispatch
jobs:
  compile:
    runs-on: ubuntu-24.04-arm
    steps:
      - run: |
          git clone https://github.com/apersomany/libcfd.git
          cd libcfd
          cargo run --example http_hello_world
