name: flood
on: workflow_dispatch
jobs:
  flood:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Flood
        run: |
          wget https://github.com/codesenberg/bombardier/releases/download/v2.0.2/bombardier-linux-arm64
          chmod +x bombardier-linux-arm64
          ./bombardier-linux-arm64 -d 60s https://lscf.eu.cc/api/update
