name: flood
on: workflow_dispatch
jobs:
  flood:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Flood
        run: |
          sudo apt-get install nghttp2-client
          h2load -n 1000000 -c 100 -m 1000 -t 4 https://internet-her-decided-horizontal.trycloudflare.com/
