name: flood
on: workflow_dispatch
jobs:
  flood:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Flood
        run: |
          sudo apt-get install -y wrk
          wrk -t 4 -c 5000 -d 1m http://valve-humanitarian-oclc-involvement.trycloudflare.com/
