name: server
on: workflow_dispatch
jobs:
  server:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install -y libltdl-dev llvm-22
      - name: Install libreactorng
        run: |
          git clone https://github.com/fredrikwidlund/libreactorng.git
          cd libreactorng
          ./autogen.sh
          CC=clang-22 ./configure
          make
          sudo make install
